### ISSUE TITLE
docker swarm

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#38]
Avec deux machines, le mieux est de se reposer sur _docker swarm_ pour tout... ou presque.

Une fois les nœuds créé, il faut mettre tout le petit monde devant être géré par traefik dans un réseau _ad hoc_ `traefik-net`. Un proposition est de créer le proxy _traefik_, puis les bases de données, puis chaque projet peut être une _stack_ en lui-même. Il suffit de créer les bons réseaux et de connecter les bons tuyaux pour isoler les projets ou non, e.g. redis.

### `proxy.yml`

```yaml
version: "3"

services:
  proxy:
    image: traefik
    hostname: proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - proxy:/etc/traefik/acme
    command: -c /etc/traefik/traefik.toml --docker.domain=srvz-webapp2.he-arc.ch --docker.swarmmode
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints: [node.role == manager]

volumes:
  proxy:

networks:
  default:
    external:
      name: traefik-net
```

### `traefik.toml`

```toml
#debug = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

traefikLogsFile = "/proc/self/fd/1"
accessLogsFile = "/proc/self/fd/1"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true

[acme]
email = "yoan.blanc@he-arc.ch"
storage = "/etc/traefik/acme/acme.json"
acmeLogging = true
onDemand = true
onHostRule = true
entryPoint = "https"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
```

### `databases.yml`

```yml
version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      labels:
        - "traefik.enable=false"

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATA=/var/lib/postgresql/data/pgdata
    ports:
      - 3306:3306
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      labels:
        - traefik.enable=false

volumes:
  mysql:
  postgres:

networks:
  default:
    external:
      name: traefik-net
```

### `admin.yml`

```yml
version: '3'

services:
  admin:
    image: php:7.1-apache
    volumes:
      - admin:/var/www/html
    environment:
      - MYSQL_HOST=databases_mysql
      - POSTGRES_HOST=databases_postgres
    ports:
      - 5432:5432
    deploy:
      labels:
        - traefik.frontend.rule=Host:admin.srvz-webapp2.he-arc.ch
        - traefik.port=80

volumes:
  admin:

networks:
  default:
    external:
      name: traefik-net
```

## Documentation

- https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/
- https://docs.docker.com/engine/swarm/stack-deploy/
- https://docs.traefik.io/user-guide/swarm-mode/
